name: CI
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  to_aws_then_azure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build React app
        run: |
          yarn install
          yarn build
      # - name: AWS, sync
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}/${GITHUB_REF##*/}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "us-east-1"
      #     SOURCE_DIR: "build"
      # - name: AWS, invalidate CF cache
      #   uses: chetan/invalidate-cloudfront-action@master
      #   env:
      #     DISTRIBUTION: E3TVX4G8S2YZV7
      #     PATHS: '/*'
      #     AWS_REGION: 'us-east-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Azure, set ENV & rebuild
        run: |
          echo "REACT_APP_ENV=azure_special" > .env
          yarn build
      - name: Upload To Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: "build"
          container_name: "$web/${GITHUB_REF##*/}"
          connection_string: ${{ secrets.ConnectionString }}
